samples: #format is sample_name: /path/to/sample.bam for both tumors and normals
  #H2K57CCX2_DTRCC10_Rkidney:  /mnt/scratch/LongRanger/H2K57CCX2_DTRCC10_Rkidney/outs/
  #H2K57CCX2_DTRCC_10_Blood:  /mnt/scratch/LongRanger/H2K57CCX2_DTRCC_10_Blood/outs/
  #H2K57CCX2_DTRCC8_Lkidney:  /mnt/scratch/LongRanger/H2K57CCX2_DTRCC8_Lkidney/outs/
  #H2K57CCX2_DTRCC_8_Blood:  /mnt/scratch/LongRanger/H2K57CCX2_DTRCC_8_Blood/outs/
   DTRCC5_LPAnode:  /mnt/storage/labs/sviswanathan/tRCC_data/DTRCC_5/DTRCC5_LPAnode.linkedReads.bam
   DTRCC5_Blood: /mnt/storage/labs/sviswanathan/tRCC_data/DTRCC_5/DTRCC5_Blood.linkedReads.bam

pairings: #format is tumor: matched_normal
  DTRCC5_LPAnode: DTRCC5_Blood
  #H2K57CCX2_DTRCC10_Rkidney: H2K57CCX2_DTRCC_10_Blood
  #H2K57CCX2_DTRCC8_Lkidney: H2K57CCX2_DTRCC_8_Blood
