samples: #format is sample_name: /path/to/sample.bam for both tumors and normals
  DTRCC6_LKidneyResection:  /home/mi724/Tools/optimalClusterSolution/
  DTRCC6_AdjNormal:  /home/mi724/Tools/optimalClusterSolution/

pairings: #format is tumor: matched_normal
  DTRCC6_LKidneyResection: DTRCC6_AdjNormal
