samples: #format is sample_name: /path/to/sample.bam for both tumors and normals
  H2K57CCX2_DTRCC6_LKidneyResection:  /mnt/scratch/LongRanger/H2K57CCX2_DTRCC6_LKidneyResection/outs/
  H2K57CCX2_DTRCC6_AdjNormal:  /mnt/scratch/LongRanger/H2K57CCX2_DTRCC6_AdjNormal/outs/

pairings: #format is tumor: matched_normal
  H2K57CCX2_DTRCC6_LKidneyResection: H2K57CCX2_DTRCC6_AdjNormal
